markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/apache/mnemonic
destination: public
source: src
exclude: [docker, BUILD.md, Gemfile*]
keep_files: [.git]
highlight_color: "#199acf"
highlight_color_hover: "#090a4f"

sass:
  style: compressed

collections:
  docs:
    output: true

